# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user1 = User.create(username: "Wilbo", first_name: "Will", last_name: "Cauthen", email: "wtf@bbq.com", city: "91041", age: 25, description: "Dead sexy", password: "password")
user2 = User.create(username: "Jamester", first_name: "Jamey", last_name: "Hollis", email: "jh@bbq.com", city: "91041", age: 20, description: "slightly less sexy", password: "password")
user3 = User.create(username: "Asteryl", first_name: "Dani", last_name: "Zaghian", email: "dz@bbq.com", city: "91041", age: 24, description: "The most sexiest", password: "password")
user4 = User.create(username: "Ryan", first_name: "Brian", last_name: "Gabot", email: "bg@bbq.com", city: "91041", age: 26, description: "The most sexist", password: "password")

genre1 = Genre.create(name: "Science Fiction")
genre2 = Genre.create(name: "MMO")
genre3 = Genre.create(name: "Table Top")
genre4 = Genre.create(name: "Fantasy")
genre5 = Genre.create(name: "RPG")
genre6 = Genre.create(name: "Fighting")
genre7 = Genre.create(name: "Action")
genre8 = Genre.create(name: "Puzzle")
genre9 = Genre.create(name: "MOBA")
genre10 = Genre.create(name: "Card")
genre11 = Genre.create(name: "Racer")
genre12 = Genre.create(name: "Shooter")

game1 = Game.create(name: "Halo: CE", min_players: 1, max_players: 16, description: "Space marines, shoot up the aliens")
game2 = Game.create(name: "Settlers of Catan", min_players: 2, max_players: 4, description: "Does anyone want a sheep??")
game3 = Game.create(name: "Dungeons & Dragons", min_players: 3, max_players: 6, description: "Table top nerd-core goofiness")
game4 = Game.create(name: "League of Legends", min_players: 1, max_players: 10, description: "Up your daily sodium intake")
game5 = Game.create(name: "Hearthstone", min_players: 1, max_players: 2, description: "Online card game with wow characters")
game6 = Game.create(name: "Super Smash Bros.", min_players: 1, max_players: 16, description: "Duke it out with your favorite nintendo characters!")
game7 = Game.create(name: "Street Fighter", min_players: 1, max_players: 2, description: "The Original fighter")
game8 = Game.create(name: "Puzzle Fighter", min_players: 1, max_players: 2, description: "Gem-destroying Fun!")
game9 = Game.create(name: "Mario Kart 8", min_players: 1, max_players: 12, description: "Karma is when you throw a banana in Mario Kart and you end up slipping on it")

group1 = Group.create(name: "D&D WDI", city: 91041, description: "Web developers by day, adventurers by late afternoon!", meet_date: "2015-11-18 10:00:00", gm: 1)
group2 = Group.create(name: "Halo LAN Party", city: 91041, description: "We all know people who play Halo are the WORST, let's put them all in a room together.", meet_date: "2015-10-10 05:00:00", gm: 2)
group3 = Group.create(name: "Catan Night", city: 91041, description: "Divide and conquer.", meet_date: "2015-08-08 06:00:00", gm: 3)
group4 = Group.create(name: "LoLganza", city: 91041, description: "Bronzies not welcome.", meet_date: "2015-11-11 10:00:00", gm: 4)
group5 = Group.create(name: "Hearthstone Tourney", city: 91041, description: "Online card tourney", meet_date: "2015-11-13 15:00:00", gm: 5)
group6 = Group.create(name: "Smash Nights", city: 91041, description: "No items. Fox only. Final Destination", meet_date: "2015-11-13 15:00:00", gm: 5)
group7 = Group.create(name: "Evo training meetup", city: 95133, description: "Gather with other fellow competitive fighter players and prepare for the biggest fighting game tournament in the world, EVO", meet_date: "2016-06-13 15:00:00", gm: 7)
group8 = Group.create(name: "Puzzle fighter meetup", city: 91041, description: "Meet up with other puzzle fighter fans", meet_date: "2015-11-26 15:00:00", gm:8)
group9 = Group.create(name: "Racing game fanatics", city: 91041, description: "Join up with other fellow racing gamer fans and play a few famous racing games such as Mario Kart", meet_date: "2015-12-13 15:00:00", gm: 9)

game1.genres.push(genre1)
game1.genres.push(genre12)
game2.genres.push(genre3)
game2.genres.push(genre4)
game3.genres.push(genre3)
game3.genres.push(genre4)
game4.genres.push(genre9)
game5.genres.push(genre10)
game6.genres.push(genre6)
game7.genres.push(genre6)
game8.genres.push(genre8)
game9.genres.push(genre11)

group1.users.push(user1, user2, user3, user4)
group2.users.push(user2, user3, user4)
group3.users.push(user1, user2, user4)
group4.users.push(user1, user2, user3)
group5.users.push(user1, user2, user3, user4)
group6.users.push(user1, user2, user3, user4)
group7.users.push(user1, user3, user4)
group8.users.push(user2, user3, user4)
group9.users.push(user1, user2, user3, user4)

game1.groups.push(group2)
game2.groups.push(group3)
game3.groups.push(group1)
game4.groups.push(group4)
game5.groups.push(group5)
game6.groups.push(group6)
game7.groups.push(group7)
game8.groups.push(group8)
game9.groups.push(group9)


